Newest oconfigure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
 #! /bin/sh
 #
 # Copyright (c) 2014, 2015, 2016 Ingo Schwarze <schwarze@openbsd.org>
-# Copyright (c) 2017 Kristaps Dzonsons <kristaps@bsd.lv>
+# Copyright (c) 2017, 2018 Kristaps Dzonsons <kristaps@bsd.lv>
 #
 # Permission to use, copy, modify, and distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -15,7 +15,7 @@
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 
-OCONFIGURE_VERSION="0.1.3"
+OCONFIGURE_VERSION="0.1.4"
 
 #
 # This script outputs two files: config.h and Makefile.configure.
@@ -132,6 +132,7 @@ done
 #----------------------------------------------------------------------
 
 HAVE_ARC4RANDOM=
+HAVE_B64_NTOP=
 HAVE_CAPSICUM=
 HAVE_ERR=
 HAVE_EXPLICIT_BZERO=
@@ -214,19 +215,28 @@ __HEREDOC__
 		return 1
 	fi
 
-	if ./test-${1} 1>&3 2>&3; then
-		echo "${1}: yes" 1>&2
-		echo "${1}: yes" 1>&3
-		echo 1>&3
-		eval HAVE_${2}=1
-		rm "test-${1}"
-		return 0
-	else
-		echo "${1}: execution failed with $?" 1>&3
-		echo 1>&3
-		rm "test-${1}"
-		return 1
-	fi
+	echo "${1}: yes" 1>&2
+	echo "${1}: yes" 1>&3
+	echo 1>&3
+	eval HAVE_${2}=1
+	rm "test-${1}"
+	return 0
+
+	# Don't actually run the test: none of our tests check for
+	# run-time behaviour.
+	# if ./test-${1} 1>&3 2>&3; then
+	# 	echo "${1}: yes" 1>&2
+	# 	echo "${1}: yes" 1>&3
+	# 	echo 1>&3
+	# 	eval HAVE_${2}=1
+	# 	rm "test-${1}"
+	# 	return 0
+	# else
+	# 	echo "${1}: execution failed with $?" 1>&3
+	# 	echo 1>&3
+	# 	rm "test-${1}"
+	# 	return 1
+	# fi
 }
 
 # Run a complete autoconfiguration test, including the check for
@@ -250,6 +260,7 @@ runtest() {
 #----------------------------------------------------------------------
 
 runtest arc4random	ARC4RANDOM			  || true
+runtest b64_ntop	B64_NTOP			  || true
 runtest capsicum	CAPSICUM			  || true
 runtest err		ERR				  || true
 runtest explicit_bzero	EXPLICIT_BZERO			  || true
@@ -331,6 +342,7 @@ __HEREDOC__
 
 cat << __HEREDOC__
 #define HAVE_ARC4RANDOM ${HAVE_ARC4RANDOM}
+#define HAVE_B64_NTOP ${HAVE_B64_NTOP}
 #define HAVE_CAPSICUM ${HAVE_CAPSICUM}
 #define HAVE_ERR ${HAVE_ERR}
 #define HAVE_EXPLICIT_BZERO ${HAVE_EXPLICIT_BZERO}
